# Generated by Django 4.2.6 on 2023-11-04 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_quantity',
        ),
    ]
