# Generated by Django 4.2.6 on 2023-11-04 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_remove_product_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='table',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='table',
            name='payment_date',
        ),
    ]
