# Generated by Django 4.2.6 on 2023-11-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_workingtable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workingtable',
            name='products',
        ),
        migrations.AddField(
            model_name='workingtable',
            name='products',
            field=models.ManyToManyField(to='restaurant.product'),
        ),
    ]
