# Generated by Django 4.2.6 on 2023-11-04 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_remove_workingtable_products_workingtable_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingtable',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
