# Generated by Django 4.2.6 on 2023-11-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_workingtable_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workingtable',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
