# Generated by Django 4.2.6 on 2023-11-04 12:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_alter_workingtable_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='workingtable',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
