# Generated by Django 4.2.6 on 2023-11-04 12:16

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_workingtable_creation_date'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='workingtable',
            managers=[
                ('working_table', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='workingtable',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
