# Generated by Django 4.2.6 on 2023-11-04 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0012_alter_workingtable_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workingtable',
            name='products',
        ),
        migrations.AddField(
            model_name='workingtable',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.product'),
        ),
        migrations.AlterField(
            model_name='workingtable',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
